lib: [
  "_build/install/default/lib/scilla-runner/META" {"META"}
  "_build/install/default/lib/scilla-runner/opam" {"opam"}
]
bin: [
  "_build/install/default/bin/eval-runner" {"eval-runner"}
  "_build/install/default/bin/scilla-checker" {"scilla-checker"}
  "_build/install/default/bin/scilla-runner" {"scilla-runner"}
  "_build/install/default/bin/type-checker" {"type-checker"}
]
doc: [
  "_build/install/default/doc/scilla-runner/LICENSE"
  "_build/install/default/doc/scilla-runner/README.md"
]
